import Head from "next/head";
import Hero from "../components/HeroMovie";
import Layout from "../components/LayoutMovie";
import LayoutTv from "../components/LayoutTv";
import Sidebar from "../components/Sidebar";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Movies2u</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Sidebar />
      {/* <LayoutTv /> */}
      {/* <Hero />  */}
    </div>
  );
}
