import Head from 'next/head';
import Homepage from '../components/Homepage';
import favicon from '../public/favicon.ico';
export default function Home() {
  return (
    <div>
      <Head>
        <title>MoviesHaven</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='shortcut icon' href={favicon} />
      </Head>

      <Homepage />
    </div>
  );
}
